def runInDocker(String image, Closure body) {
  docker.image(image).inside {
    body()
  }
}

pipeline {
  agent any

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    stage('Lint') {
      steps {
        script {
          runInDocker('maven:3.8.6-openjdk-11-slim') {
            sh 'apt-get update && apt-get install -y make'
            sh 'make lint'
          }
        }
      }
    }

    stage('Test') {
      steps {
        script {
          runInDocker('maven:3.8.6-openjdk-11-slim') {
            sh 'apt-get update && apt-get install -y make'
            sh 'make test'
          }
        }
      }
    }
  }
}


